// ==============================================================================
// Mock Seed Data for HVE Work Frontend (Offline & Demo Mode)
// ==============================================================================

import type { DocumentItem, TaskItem } from './types';

export const MOCK_USERS = {
  employee: {
    id: 1,
    name: 'Nguyễn Văn An',
    email: 'nv1@huyvoeducation.vn',
    roles: ['employee'],
    departmentId: 1,
    department: { id: 1, name: 'Phòng Kinh doanh & Tuyển sinh', code: 'KD' },
  },
  dept_head: {
    id: 2,
    name: 'Trần Minh Tuấn',
    email: 'tp_it@huyvoeducation.vn',
    roles: ['department_head', 'employee'],
    departmentId: 2,
    department: { id: 2, name: 'Phòng Công nghệ Thông tin', code: 'IT' },
  },
  accountant: {
    id: 3,
    name: 'Trần Thị Mai',
    email: 'ketoan@huyvoeducation.vn',
    roles: ['accountant', 'department_head'],
    departmentId: 3,
    department: { id: 3, name: 'Phòng Tài chính - Kế toán', code: 'TC' },
  },
  legal: {
    id: 4,
    name: 'Hoàng Kim Ngân',
    email: 'phapche@huyvoeducation.vn',
    roles: ['legal', 'employee'],
    departmentId: 4,
    department: { id: 4, name: 'Ban Pháp chế & Thẩm định', code: 'PC' },
  },
  ceo: {
    id: 5,
    name: 'Võ Huy Định',
    email: 'ceo@huyvoeducation.vn',
    roles: ['ceo'],
    departmentId: null,
    department: { id: 0, name: 'Ban Giám Đốc', code: 'BGD' },
  },
  it_admin: {
    id: 6,
    name: 'Lê Hoàng Minh',
    email: 'admin@huyvoeducation.vn',
    roles: ['it_admin'],
    departmentId: 2,
    department: { id: 2, name: 'Phòng Công nghệ Thông tin', code: 'IT' },
  },
};

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: 1,
    code: 'DNTT-2026-001',
    title: 'Thanh toán chi phí thuê hạ tầng máy chủ Staging Q3/2026',
    type: 'payment_request',
    status: 'Chờ duyệt',
    version: 1,
    createdById: 1,
    createdAt: '2026-09-15T08:30:00Z',
    createdBy: {
      id: 1,
      name: 'Nguyễn Văn An',
      email: 'nv1@huyvoeducation.vn',
      department: { id: 1, name: 'Phòng Kinh doanh & Tuyển sinh', code: 'KD' },
    },
    dataJson: {
      amount: 15500000,
      receiver: 'Công ty Cổ phần Công nghệ Điện toán Đám mây VinaCloud',
      bankName: 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)',
      bankAccount: '0071001234567',
      content: 'Thanh toán phí duy trì cụm máy chủ Staging và CDN phục vụ nền tảng tuyển sinh trực tuyến HVE đợt tuyển sinh mùa thu 2026.',
      deadline: '2026-09-20',
    },
    attachments: [
      {
        id: 101,
        fileName: 'Hoa_don_GTGT_VinaCloud_HD1289.pdf',
        fileUrl: '/uploads/demo-invoice.pdf',
        size: 2450000,
        mimeType: 'application/pdf',
        uploadedById: 1,
        uploadedAt: '2026-09-15T08:30:00Z',
        uploadedBy: {
          id: 1,
          name: 'Nguyễn Văn An',
          email: 'nv1@huyvoeducation.vn',
          roles: [{ name: 'employee' }],
        },
      },
    ],
    steps: [
      {
        id: 11,
        stepOrder: 1,
        roleRequired: 'department_head',
        status: 'approved',
        actedById: 2,
        actedBy: {
          id: 2,
          name: 'Trần Minh Tuấn',
          email: 'tp_it@huyvoeducation.vn',
          roles: [{ name: 'department_head' }, { name: 'employee' }],
        },
        actedAt: '2026-09-15T09:15:00Z',
        comment: 'Đã kiểm tra hồ sơ và bảng kê chi tiết, đồng ý phê duyệt.',
      },
      {
        id: 12,
        stepOrder: 2,
        roleRequired: 'accountant',
        status: 'pending',
      },
      {
        id: 13,
        stepOrder: 3,
        roleRequired: 'ceo',
        status: 'not_started',
      },
    ],
  },
  {
    id: 2,
    code: 'DNTT-2026-002',
    title: 'Mua bản quyền bộ công cụ phần mềm Figma Enterprise & Zoom Pro',
    type: 'payment_request',
    status: 'Đã duyệt',
    version: 1,
    createdById: 2,
    createdAt: '2026-09-12T10:00:00Z',
    createdBy: {
      id: 2,
      name: 'Trần Minh Tuấn',
      email: 'tp_it@huyvoeducation.vn',
      department: { id: 2, name: 'Phòng Công nghệ Thông tin', code: 'IT' },
    },
    dataJson: {
      amount: 8800000,
      receiver: 'Công ty TNHH Giải pháp Phần mềm Trí Việt',
      bankName: 'Ngân hàng Quân Đội (MB Bank)',
      bankAccount: '19001239999',
      content: 'Gia hạn gói 5 licenses Figma Design và 3 tài khoản Zoom Pro 300 người phục vụ giảng dạy trực tuyến.',
      deadline: '2026-09-14',
    },
    attachments: [
      {
        id: 102,
        fileName: 'Chung_tu_thanh_toan_Software_2026.pdf',
        fileUrl: '/uploads/demo-software.pdf',
        size: 1800000,
        mimeType: 'application/pdf',
        uploadedById: 3,
        uploadedAt: '2026-09-12T14:32:00Z',
        uploadedBy: {
          id: 3,
          name: 'Trần Thị Mai',
          email: 'ketoan@huyvoeducation.vn',
          roles: [{ name: 'accountant' }, { name: 'department_head' }],
        },
      },
    ],
    steps: [
      {
        id: 21,
        stepOrder: 1,
        roleRequired: 'department_head',
        status: 'approved',
        actedById: 2,
        actedBy: {
          id: 2,
          name: 'Trần Minh Tuấn',
          email: 'tp_it@huyvoeducation.vn',
          roles: [{ name: 'department_head' }, { name: 'employee' }],
        },
        actedAt: '2026-09-12T10:05:00Z',
        comment: 'Phê duyệt nội bộ bộ phận IT.',
      },
      {
        id: 22,
        stepOrder: 2,
        roleRequired: 'accountant',
        status: 'approved',
        actedById: 3,
        actedBy: {
          id: 3,
          name: 'Trần Thị Mai',
          email: 'ketoan@huyvoeducation.vn',
          roles: [{ name: 'accountant' }, { name: 'department_head' }],
        },
        actedAt: '2026-09-12T14:30:00Z',
        comment: 'Hồ sơ hóa đơn hợp lệ, số dư ngân sách đủ điều kiện chi trả.',
      },
      {
        id: 23,
        stepOrder: 3,
        roleRequired: 'ceo',
        status: 'approved',
        actedById: 5,
        actedBy: {
          id: 5,
          name: 'Võ Huy Định',
          email: 'ceo@huyvoeducation.vn',
          roles: [{ name: 'ceo' }],
        },
        actedAt: '2026-09-13T09:00:00Z',
        comment: 'Đồng ý phê duyệt thanh toán.',
      },
    ],
  },
  {
    id: 3,
    code: 'DX-2026-001',
    title: 'Tờ trình phê duyệt phương án nâng cấp trang thiết bị phòng Lab Đào tạo',
    type: 'proposal',
    status: 'Chờ duyệt',
    version: 1,
    createdById: 2,
    createdAt: '2026-09-14T14:00:00Z',
    createdBy: {
      id: 2,
      name: 'Trần Minh Tuấn',
      email: 'tp_it@huyvoeducation.vn',
      department: { id: 2, name: 'Phòng Công nghệ Thông tin', code: 'IT' },
    },
    dataJson: {
      content: 'Kính gửi Ban Giám đốc: Hiện tại phòng Lab 02 đã vận hành 3 năm, dàn máy trạm có hiện tượng chậm khi chạy các bộ môn AI/Data. Kính đề nghị nâng cấp RAM 32GB và ổ cứng NVMe cho 20 máy trạm, tổng dự toán 60 triệu VNĐ.',
    },
    attachments: [],
    steps: [
      {
        id: 31,
        stepOrder: 1,
        roleRequired: 'department_head',
        status: 'approved',
        actedById: 2,
        actedAt: '2026-09-14T14:15:00Z',
        comment: 'Đã khảo sát thực tế và báo giá từ 3 nhà cung cấp.',
      },
      {
        id: 32,
        stepOrder: 2,
        roleRequired: 'ceo',
        status: 'pending',
      },
    ],
  },
  {
    id: 4,
    code: 'HD-2026-001',
    title: 'Hợp đồng hợp tác đào tạo nguồn nhân lực số với Tập đoàn Công nghệ Tân Á',
    type: 'contract',
    status: 'Chờ duyệt',
    version: 1,
    createdById: 1,
    createdAt: '2026-09-15T11:00:00Z',
    createdBy: {
      id: 1,
      name: 'Nguyễn Văn An',
      email: 'nv1@huyvoeducation.vn',
      department: { id: 1, name: 'Phòng Kinh doanh & Tuyển sinh', code: 'KD' },
    },
    dataJson: {
      partner: 'Tập đoàn Công nghệ Tân Á Đại Thành',
      value: 350000000,
      startDate: '2026-10-01',
      endDate: '2027-09-30',
      manager: 'Nguyễn Văn An',
      notes: 'Hợp đồng trọn gói 12 tháng đào tạo 150 nhân sự chuyển đổi số.',
    },
    attachments: [
      {
        id: 104,
        fileName: 'Du_thao_Hop_dong_TanA_HVE_Final.docx',
        fileUrl: '/uploads/demo-contract.docx',
        size: 3200000,
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      },
    ],
    steps: [
      {
        id: 41,
        stepOrder: 1,
        roleRequired: 'department_head',
        status: 'approved',
        actedById: 2,
        actedAt: '2026-09-15T11:30:00Z',
        comment: 'Đồng ý về phạm vi kỹ thuật đào tạo.',
      },
      {
        id: 42,
        stepOrder: 2,
        roleRequired: 'legal',
        status: 'pending',
      },
      {
        id: 43,
        stepOrder: 3,
        roleRequired: 'accountant',
        status: 'not_started',
      },
      {
        id: 44,
        stepOrder: 4,
        roleRequired: 'ceo',
        status: 'not_started',
      },
    ],
  },
  {
    id: 5,
    code: 'HD-2026-002',
    title: 'Hợp đồng thuê hạ tầng Cloud AWS HVE Core System',
    type: 'contract',
    status: 'Đã duyệt',
    version: 1,
    createdById: 2,
    createdAt: '2025-10-01T08:00:00Z',
    createdBy: {
      id: 2,
      name: 'Trần Minh Tuấn',
      email: 'tp_it@huyvoeducation.vn',
      department: { id: 2, name: 'Phòng Công nghệ Thông tin', code: 'IT' },
    },
    dataJson: {
      partner: 'Amazon Web Services Vietnam LLC',
      value: 120000000,
      startDate: '2025-10-01',
      endDate: '2026-09-30',
      manager: 'Trần Minh Tuấn',
      notes: 'Hợp đồng sắp hết hạn trong vòng 14 ngày tới (≤30 ngày). Cần chuẩn bị phụ lục gia hạn.',
    },
    isExpiringSoon: true,
    expiringStatus: 'expiring_soon',
    daysRemaining: 14,
    attachments: [],
    steps: [
      {
        id: 51,
        stepOrder: 1,
        roleRequired: 'department_head',
        status: 'approved',
        actedById: 2,
        actedAt: '2025-10-01T08:30:00Z',
        comment: 'Phê duyệt kỹ thuật.',
      },
      {
        id: 52,
        stepOrder: 2,
        roleRequired: 'legal',
        status: 'approved',
        actedById: 4,
        actedAt: '2025-10-01T09:00:00Z',
        comment: 'Điều khoản hợp đồng tiêu chuẩn quốc tế hợp lệ.',
      },
      {
        id: 53,
        stepOrder: 3,
        roleRequired: 'accountant',
        status: 'approved',
        actedById: 3,
        actedAt: '2025-10-01T10:00:00Z',
        comment: 'Ngân sách IT đã được duyệt hàng năm.',
      },
      {
        id: 54,
        stepOrder: 4,
        roleRequired: 'ceo',
        status: 'approved',
        actedById: 5,
        actedAt: '2025-10-01T11:00:00Z',
        comment: 'Phê duyệt ký kết.',
      },
    ],
  },
];

export const MOCK_TASKS: TaskItem[] = [
  {
    id: 1,
    code: 'CV-2026-001',
    title: 'Hoàn thiện hồ sơ kiểm toán tài chính 6 tháng đầu năm 2026',
    description: 'Rà soát toàn bộ các khoản thu chi, đối chiếu số dư ngân hàng và báo cáo tài chính nội bộ.',
    priority: 'high',
    status: 'Chờ duyệt',
    progressPercent: 90,
    startDate: '2026-09-01T00:00:00Z',
    dueDate: '2026-09-18T00:00:00Z',
    isOverdue: false,
    createdById: 5,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-15T00:00:00Z',
    assignee: { id: 3, name: 'Trần Thị Mai', email: 'ketoan@huyvoeducation.vn', departmentId: 2 },
    createdBy: { id: 5, name: 'Võ Huy Định', email: 'ceo@huyvoeducation.vn' },
    subTasks: [
      {
        id: 101,
        code: 'CV-2026-001-01',
        title: 'Đối soát sao kê ngân hàng 4 tài khoản',
        priority: 'high',
        status: 'Hoàn thành',
        progressPercent: 100,
        assignee: { id: 3, name: 'Trần Thị Mai' },
      },
      {
        id: 102,
        code: 'CV-2026-001-02',
        title: 'Tổng hợp bảng kê công nợ đối tác tuyển sinh',
        priority: 'normal',
        status: 'Đang làm',
        progressPercent: 80,
        assignee: { id: 3, name: 'Trần Thị Mai' },
      },
    ],
  },
  {
    id: 2,
    code: 'CV-2026-002',
    title: 'Kiểm thử ứng dụng PWA và kiểm tra tính năng Web Push trên di động',
    description: 'Chạy thử nghiệm cài đặt ứng dụng lên màn hình chính và nhận thông báo đẩy tức thời.',
    priority: 'normal',
    status: 'Hoàn thành',
    progressPercent: 100,
    startDate: '2026-09-10T00:00:00Z',
    dueDate: '2026-09-16T00:00:00Z',
    isOverdue: false,
    createdById: 2,
    createdAt: '2026-09-10T00:00:00Z',
    updatedAt: '2026-09-16T00:00:00Z',
    assignee: { id: 1, name: 'Nguyễn Văn An', email: 'nv1@huyvoeducation.vn', departmentId: 1 },
    createdBy: { id: 2, name: 'Trần Minh Tuấn', email: 'tp_it@huyvoeducation.vn' },
  },
  {
    id: 3,
    code: 'CV-2026-003',
    title: 'Soạn thảo bộ quy chuẩn thẩm định pháp lý đối tác đào tạo 2026',
    description: 'Biên soạn khung pháp lý, điều khoản bảo mật thông tin học viên và mẫu cam kết.',
    priority: 'urgent',
    status: 'Đang làm',
    progressPercent: 40,
    startDate: '2026-09-05T00:00:00Z',
    dueDate: '2026-09-14T00:00:00Z',
    isOverdue: true,
    createdById: 5,
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-14T00:00:00Z',
    assignee: { id: 4, name: 'Hoàng Kim Ngân', email: 'phapche@huyvoeducation.vn', departmentId: 4 },
    createdBy: { id: 5, name: 'Võ Huy Định', email: 'ceo@huyvoeducation.vn' },
  },
  {
    id: 4,
    code: 'CV-2026-004',
    title: 'Khảo sát nhu cầu đào tạo nâng cao kỹ năng nội bộ định kỳ',
    description: 'Thu thập ý kiến đóng góp từ các phòng ban để xây dựng kế hoạch đào tạo Quý 4/2026.',
    priority: 'normal',
    status: 'Đang làm',
    progressPercent: 65,
    startDate: '2026-09-12T00:00:00Z',
    dueDate: '2026-09-25T00:00:00Z',
    isOverdue: false,
    recurrenceRule: 'monthly',
    createdById: 2,
    createdAt: '2026-09-12T00:00:00Z',
    updatedAt: '2026-09-15T00:00:00Z',
    assignee: { id: 1, name: 'Nguyễn Văn An', email: 'nv1@huyvoeducation.vn' },
    createdBy: { id: 2, name: 'Trần Minh Tuấn', email: 'tp_it@huyvoeducation.vn' },
  },
];

export const MOCK_DASHBOARD_DATA = {
  capabilities: {
    canViewCompany: true,
    canViewFinancials: true,
    canViewLegal: true,
  },
  scope: { label: 'Toàn công ty' },
  actionRequired: {
    pendingApprovalsCount: 2,
    pendingDocuments: [
      { id: 1, code: 'DNTT-2026-001', title: 'Thanh toán chi phí thuê hạ tầng máy chủ Staging Q3/2026', createdBy: { name: 'Nguyễn Văn An' } },
      { id: 4, code: 'HD-2026-001', title: 'Hợp đồng hợp tác đào tạo nguồn nhân lực số với Tập đoàn Tân Á', createdBy: { name: 'Nguyễn Văn An' } },
    ],
    expiringContractsCount: 1,
    expiringContracts: [
      { id: 5, code: 'HD-2026-002', title: 'Hợp đồng thuê hạ tầng Cloud AWS HVE Core System', dataJson: { endDate: '2026-09-30' } },
    ],
    escalatedTasksCount: 1,
    escalatedTasks: [
      { id: 3, code: 'CV-2026-003', title: 'Soạn thảo bộ quy chuẩn thẩm định pháp lý đối tác 2026', assignee: { name: 'Hoàng Kim Ngân', department: { name: 'Ban Pháp chế' } } },
    ],
    overdueTasksCount: 1,
  },
  metrics: {
    documents: { pending: 3, approved: 12, draft: 1 },
    tasks: { inProgress: 8, overdue: 1, completed: 15 },
  },
  projectStats: [
    { id: 1, code: 'HB', name: 'Hồ bơi', completionRate: 94, completedTasks: 16, totalTasks: 17 },
    { id: 2, code: 'TPS1', name: 'Văn phòng TPS1', completionRate: 88, completedTasks: 14, totalTasks: 16 },
    { id: 3, code: 'GD', name: 'Giáo dục', completionRate: 75, completedTasks: 9, totalTasks: 12 },
  ],
};

export const MOCK_REPORTS_SUMMARY = {
  documents: {
    total: 16,
    approvalRate: 87.5,
    pending: 3,
    avgApprovalTimeHours: 4.2,
    items: [
      { id: 1, code: 'DNTT-2026-001', title: 'Thanh toán chi phí thuê server Staging Q3/2026', type: 'payment_request', creator: 'Nguyễn Văn An', department: 'Kinh doanh', createdAt: '2026-09-15', status: 'Chờ duyệt' },
      { id: 2, code: 'DNTT-2026-002', title: 'Mua bản quyền bộ công cụ Figma & Zoom Pro', type: 'payment_request', creator: 'Trần Minh Tuấn', department: 'Công nghệ Thông tin', createdAt: '2026-09-12', status: 'Đã duyệt' },
      { id: 3, code: 'DX-2026-001', title: 'Tờ trình nâng cấp phòng Lab Đào tạo', type: 'proposal', creator: 'Trần Minh Tuấn', department: 'Công nghệ Thông tin', createdAt: '2026-09-14', status: 'Chờ duyệt' },
      { id: 4, code: 'HD-2026-001', title: 'Hợp đồng hợp tác đào tạo Tân Á Đại Thành', type: 'contract', creator: 'Nguyễn Văn An', department: 'Kinh doanh', createdAt: '2026-09-15', status: 'Chờ duyệt' },
      { id: 5, code: 'HD-2026-002', title: 'Hợp đồng thuê hạ tầng Cloud AWS HVE', type: 'contract', creator: 'Trần Minh Tuấn', department: 'Công nghệ Thông tin', createdAt: '2025-10-01', status: 'Đã duyệt' },
    ],
  },
  tasks: {
    total: 24,
    completionRate: 83.3,
    inProgress: 8,
    overdue: 1,
    items: [
      { id: 1, code: 'CV-2026-001', title: 'Hoàn thiện hồ sơ kiểm toán tài chính 6 tháng', assignee: 'Trần Thị Mai', department: 'Tài chính - Kế toán', dueDate: '2026-09-18', progressPercent: 90, status: 'Chờ duyệt', isOverdue: false },
      { id: 2, code: 'CV-2026-002', title: 'Kiểm thử ứng dụng PWA và Web Push di động', assignee: 'Nguyễn Văn An', department: 'Kinh doanh', dueDate: '2026-09-16', progressPercent: 100, status: 'Hoàn thành', isOverdue: false },
      { id: 3, code: 'CV-2026-003', title: 'Soạn thảo quy chuẩn thẩm định pháp lý đối tác', assignee: 'Hoàng Kim Ngân', department: 'Ban Pháp chế', dueDate: '2026-09-14', progressPercent: 40, status: 'Đang làm', isOverdue: true },
      { id: 4, code: 'CV-2026-004', title: 'Khảo sát nhu cầu đào tạo nội bộ định kỳ', assignee: 'Nguyễn Văn An', department: 'Kinh doanh', dueDate: '2026-09-25', progressPercent: 65, status: 'Đang làm', isOverdue: false },
    ],
  },
  contracts: {
    total: 8,
    totalValue: 1250000000,
    expiringSoonCount: 1,
    items: [
      { id: 4, code: 'HD-2026-001', title: 'Hợp đồng đào tạo Tân Á Đại Thành', partner: 'Tập đoàn Tân Á', value: 350000000, startDate: '2026-10-01', endDate: '2027-09-30', manager: 'Nguyễn Văn An', isExpiringSoon: false },
      { id: 5, code: 'HD-2026-002', title: 'Hợp đồng thuê hạ tầng Cloud AWS HVE', partner: 'Amazon Web Services', value: 120000000, startDate: '2025-10-01', endDate: '2026-09-30', manager: 'Trần Minh Tuấn', isExpiringSoon: true },
      { id: 6, code: 'HD-2026-003', title: 'Hợp đồng cung cấp giáo trình tiếng Anh HVE Cambridge', partner: 'NXB Giáo Dục Quốc Tế', value: 280000000, startDate: '2026-01-15', endDate: '2027-01-15', manager: 'Nguyễn Văn An', isExpiringSoon: false },
    ],
  },
  auditLogs: [
    { id: 501, createdAt: '2026-09-16T09:30:00Z', actor: { name: 'Trần Minh Tuấn' }, entityType: 'Document', entityId: 1, action: 'APPROVE_STEP_1', ip: '192.168.1.45', afterJson: { status: 'approved', comment: 'Đã duyệt bước 1' } },
    { id: 502, createdAt: '2026-09-15T15:20:00Z', actor: { name: 'Võ Huy Định' }, entityType: 'Task', entityId: 3, action: 'ESCALATE_ALERT', ip: '14.225.2.10', afterJson: { notice: 'Cảnh báo quá hạn leo thang CEO' } },
    { id: 503, createdAt: '2026-09-15T08:30:00Z', actor: { name: 'Nguyễn Văn An' }, entityType: 'Document', entityId: 1, action: 'SUBMIT_FOR_APPROVAL', ip: '192.168.1.102', afterJson: { code: 'DNTT-2026-001' } },
  ],
};
